language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm


notifications:
  on_success: always
  on_failure: always
  email:
    - tim.cook@hightail.com


before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev


script: phpunit

allow_failures:
  - php: 5.6
  - php: hhvm

fast_finish: true
